base_url: 
domain: 
res_base_url: resources
highlighter: pygments
markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot


# course
course_number: CSCI-UA.0002
course_section: "008"
course_name: Introduction to Computer Programming
course_semester: Fall 2015
course_time: "Mondays and Wednesdays, 12:30PM - 1:45PM"
course_room: WWH 317
course_url: http://foureyes.github.io/csci-ua.0002-fall2015-008

# office hours
office_hours: "Mondays and Wednesdays from 2:00pm to 3:00pm and Thursdays 11:00AM to 12:00PM"
office_hours_room: WWH 423

# finals
final_schedule: http://www.cs.nyu.edu/webapps/fall2015/Undergraduate/final_exams 
final_date: Thursday, May 14th
final_time: 12:00PM - 1:50PM
final_room: WWH 317


# books
bookq: Starting Out with Python
bookt: How to Think Like a Computer Scientist

departmental_syllabus: "http://cs.nyu.edu/courses/fall15/CSCI-UA.0002-002/common_syllabus/"

# manual section change
# http://foureyes.github.io/csci-ua.0002-spring2015-008 -> http://foureyes.github.io/csci-ua.0002-fall2014-010
